### ISSUE TITLE
Unforgiving driver/rider matching

### ISSUE THREAD

**Issue by cwentland0** [nzsilverman/climbing_carpools#6]
On those driver/riders who leave at exactly the same time and location are matched, with the sole exceptions of `rider.dept_time == Dept_Time.BEFORE_730 and driver.dept_time == Dept_Time.AT_730` and `rider.loc == Loc.NORTH_AND_CENTRAL and driver.loc == Loc.CENTRAL`. More flexible options might be included in the Google Form (e.g. any time within a certain range, any pickup location) and incorporated into `find_best_match()` to accommodate more flexible riders.

**Comment by nzsilverman** [comment]
My idea with this was that if a rider selected they would be ok with leaving from north and central then they would first try and be matched with a driver who was leaving from north, and if none were available, then one from central. 

For time, if a driver is leaving before 730 in the window from 6-730 and a rider chose to leave at 7:30, then I am **NOT** including them in that lottery, since the rider cannot leave before 7:30 and the driver is. However, for the case where a rider wants to leave before 7:30 and a driver wants to leave at 7:30, I am including the rider in that raffle. That seemed logical to me, but I see where you could disagree with that. 

Honestly I am not a huge fan of how we are collecting the information, it does not lend itself to this kind of flexibilty very well
