### ISSUE TITLE
Change Google Form

### ISSUE THREAD

**Issue by jonahrosenblum** [nzsilverman/climbing_carpools#9]
If you try to use the current google form there are fields marked "driver use only" or "rider use only." If one accidentally selects an option in these questions they will be unable to unselect their mistake. Is it possible to add functionality to the radio buttons on the form so that they can be unselected? Using checkboxes might lead to issues if people select more than one.

**Comment by nzsilverman** [comment]
I agree this is not great, but I don't think there is anything we can do to change that, since we don't want a checkbox as you pointed out. I think this is more a flaw of the google form, and something we will just have to live with. If a user enters something wrong into those fields (ie a rider modifies a driver field), the program ignores the data anyways. 

The biggest solution I see to this would be to write our own data collection software. What I envision this looking like would be a rewrite of the climbing website, hosted on something like aws and using something like react for the frontend, so we can make a nice gui that gives more flexibility for our options. This is where I envision the software going,  so for now I am not super concerned about the radio buttons. I will make a new issue detailing where I see this migrating towards. For now, the version currently needs to work, and be easy to use. 

If you think of changes we could make to the form that would be helpful, we should do that. Granted it would involve rewriting parts of read_`responses.py`, but that seems like a downfall of the current software in that it is not as modular as it could be, partly because of the google form

**Comment by jonahrosenblum** [comment]
I do like the idea of making our own form on the climbing club website, but keep in mind HTML radio buttons will act the same way. One idea I just thought of is to use conditional questions/pages for the form - I'm pretty sure you can set it up so that certain questions/pages of a google form only appear if another certain option is select, no?

**Comment by nzsilverman** [comment]
This issue is still relevant- version 2 of the software needs to include changes to the google form that address Jonahs concerns. This could be addressed by changing the google form, or maybe splitting the google form into 2 forms- one for drivers and one for riders to fill out. Although this has its own drawbacks- what if a person wants to be a rider and a driver on different days of the week? I bet we can figure out how to address this, but worth keeping in mind

**Comment by rkalnins** [comment]
# New Google Form idea

Form is shorter and simpler. Makes use of the checkbox grid for selecting days and locations.
Uses checkboxes for riders to select desirable departure times.
Uses dropdown for drivers to select single departure time.

[Form edit](https://docs.google.com/forms/d/155N7-36aqYZ9TrQ7XXB_Mq6I7r7OvL7ir2m5cBhRy-E/edit)
[Responses](https://docs.google.com/spreadsheets/d/1DHdkYQNSQLVaAxz5nTbh_-WkNt3i7TlbG4PBPQft1MM/edit#gid=1115703063)
[Fillable](https://forms.gle/ZCakwpWrdz96Vh5E6)

**Comment by rkalnins** [comment]
Currently in use and working well. Form is like [this](https://docs.google.com/forms/d/155N7-36aqYZ9TrQ7XXB_Mq6I7r7OvL7ir2m5cBhRy-E/edit) (same as previous comment on this issue).
